

export const LOAN_GET_REQUEST = 'LOAN_GET_REQUEST'
export const LOAN_GET_FAIL = 'LOAN_GET_FAIL'
export const LOAN_GET_SUCCESS = 'LOAN_GET_SUCCESS'

export const LOAN_CREATE_REQUEST = 'LOAN_CREATE_REQUEST'
export const LOAN_CREATE_FAIL = 'LOAN_CREATE_FAIL'
export const LOAN_CREATE_SUCCESS = 'LOAN_CREATE_SUCCESS'

export const LOAN_APPROVED_GET_REQUEST = 'LOAN_APPROVED_GET_REQUEST'
export const LOAN_APPROVED_GET_FAIL = 'LOAN_APPROVED_GET_FAIL'
export const LOAN_APPROVED_GET_SUCCESS = 'LOAN_APPROVED_GET_SUCCESS'

export const LOAN_APPROVE_REQUEST = 'LOAN_APPROVE_REQUEST'
export const LOAN_APPROVE_FAIL = 'LOAN_APPROVE_FAIL'
export const LOAN_APPROVE_SUCCESS = 'LOAN_APPROVE_SUCCESS'

export const LOAN_DELETE_REQUEST = 'LOAN_DELETE_REQUEST'
export const LOAN_DELETE_FAIL = 'LOAN_DELETE_FAIL'
export const LOAN_DELETE_SUCCESS = 'LOAN_DELETE_SUCCESS'

export const LOAN_SPECIFIC_REQUEST = 'LOAN_SPECIFIC_REQUEST'
export const LOAN_SPECIFIC_FAIL = 'LOAN_SPECIFIC_FAIL'
export const LOAN_SPECIFIC_SUCCESS = 'LOAN_SPECIFIC_SUCCESS'
